export const resources = [];

populateResource();

function populateResource() {
  resources.push(
    ...[
      {
        id: 0,
        resourceType: 'Mental Health & Substance Use',
        name: 'Greater Cincinnati Behavioral Health Services',
        address: '1501 Madison Rd, Cincinnati, OH 45206',
        Lat: 39.1279,
        Lon: -84.4766,
        phone: '(513) 354-5200',
        description:
          'Behavioral health and addiction recovery programs for low-income and homeless individuals.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 1,
        resourceType: 'Mental Health & Substance Use',
        name: 'Talbert House Addiction Services',
        address: '2600 Victory Parkway, Cincinnati, OH 45206',
        Lat: 39.127,
        Lon: -84.488,
        phone: '(513) 281-2273',
        description:
          'Outpatient and residential treatment for substance use disorders, serving vulnerable populations.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 2,
        resourceType: 'Mental Health & Substance Use',
        name: 'UMADAOP',
        address: '199 William Howard Taft Rd, Cincinnati, OH 45219',
        Lat: 39.1298,
        Lon: -84.5112,
        phone: '(513) 541-7099',
        description:
          'Outreach and prevention programs for minority youth and families impacted by addiction.',
        hours: 'Mon-Fri 9am-5pm',
      },
      {
        id: 3,
        resourceType: 'Healthcare',
        name: 'Crossroad Health Center',
        address: '5 E. Liberty St, Cincinnati, OH 45202',
        Lat: 39.1152,
        Lon: -84.512,
        phone: '(513) 381-2247',
        description:
          'Community health clinic providing primary care for uninsured and homeless individuals.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 4,
        resourceType: 'Healthcare',
        name: 'Good Samaritan Free Health Center',
        address: '3727 St. Lawrence Ave, Cincinnati, OH 45205',
        Lat: 39.104,
        Lon: -84.548,
        phone: '(513) 246-6880',
        description: 'Free medical, dental, and vision care for low-income residents.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 5,
        resourceType: 'Healthcare',
        name: 'UC Health Hoxworth Clinic',
        address: '3130 Highland Ave, Cincinnati, OH 45219',
        Lat: 39.1395,
        Lon: -84.5035,
        phone: '(513) 584-1000',
        description:
          'Safety-net clinic offering primary care and specialty services for underserved populations.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 6,
        resourceType: 'Employment Assistance',
        name: 'OhioMeansJobs Cincinnati - Hamilton County',
        address: '1916 Central Parkway, Cincinnati, OH 45214',
        Lat: 39.116,
        Lon: -84.529,
        phone: '(513) 946-7200',
        description:
          'Job leads, workshops, and career coaching for unemployed and underemployed residents.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 7,
        resourceType: 'Employment Assistance',
        name: 'Cincinnati Goodwill Employment Services',
        address: '1065 Reading Rd, Cincinnati, OH 45215',
        Lat: 39.236,
        Lon: -84.456,
        phone: '(513) 771-4800',
        description:
          'Workforce development and job placement for individuals facing barriers to employment.',
        hours: 'Mon-Fri 8am-4:30pm',
      },
      {
        id: 8,
        resourceType: 'Employment Assistance',
        name: 'Community Action Agency - Fresh Start Program',
        address: '1740 Langdon Farm Rd, Cincinnati, OH 45237',
        Lat: 39.191,
        Lon: -84.456,
        phone: '(513) 569-1840',
        description: 'Employment readiness and training for ex-offenders and low-income residents.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 9,
        resourceType: 'Identification',
        name: 'Freestore Foodbank - Liberty St ID Assistance',
        address: '112 E. Liberty St, Cincinnati, OH 45202',
        Lat: 39.115,
        Lon: -84.515,
        phone: '(513) 357-4600',
        description:
          'Provides vouchers to help homeless individuals obtain birth certificates and state IDs.',
        hours: 'Mon-Fri 8am-3:45pm',
      },
      {
        id: 10,
        resourceType: 'Identification',
        name: 'St. Vincent de Paul ID Program',
        address: '1125 Bank St, Cincinnati, OH 45202',
        Lat: 39.1165,
        Lon: -84.537,
        phone: '(513) 562-8841',
        description: 'Monthly assistance with birth certificates and identification documents.',
        hours: 'First Thursday 8am-11am',
      },
      {
        id: 11,
        resourceType: 'Identification',
        name: 'Salvation Army Social Services',
        address: '131 E. 12th St, Cincinnati, OH 45202',
        Lat: 39.1099,
        Lon: -84.511,
        phone: '(513) 762-5660',
        description: 'Helps low-income individuals secure identification and essential documents.',
        hours: 'Mon-Fri 8:15am open',
      },
      {
        id: 12,
        resourceType: 'Outreach & Drop-in Centers',
        name: 'Shelterhouse (Drop Inn Center)',
        address: '411 Gest St, Cincinnati, OH 45203',
        Lat: 39.107,
        Lon: -84.537,
        phone: '(513) 721-0643',
        description: 'Emergency shelter and drop-in services for homeless adults.',
        hours: '24/7',
      },
      {
        id: 13,
        resourceType: 'Outreach & Drop-in Centers',
        name: 'City Gospel Mission',
        address: '1805 Dalton St, Cincinnati, OH 45214',
        Lat: 39.109,
        Lon: -84.537,
        phone: '(513) 241-5525',
        description:
          'Drop-in support, meals, recovery programs, and outreach for homeless individuals.',
        hours: 'Mon-Fri 9am-5pm',
      },
      {
        id: 14,
        resourceType: 'Outreach & Drop-in Centers',
        name: 'St. Vincent de Paul Don & Phyllis Neyer Outreach Center',
        address: '1146 Bank St, Cincinnati, OH 45214',
        Lat: 39.116,
        Lon: -84.5375,
        phone: '(513) 562-8841',
        description: 'Outreach, case management, and basic needs for impoverished families.',
        hours: 'Mon-Fri 8:30am-4pm',
      },
      {
        id: 15,
        resourceType: 'Youth Assistance',
        name: 'Children’s Home of Cincinnati',
        address: '5050 Madison Rd, Cincinnati, OH 45227',
        Lat: 39.156,
        Lon: -84.395,
        phone: '(513) 272-2800',
        description: 'Behavioral health, foster care, and educational support for at-risk youth.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 16,
        resourceType: 'Youth Assistance',
        name: 'Boys & Girls Clubs of Greater Cincinnati',
        address: '600 Dalton Ave, Cincinnati, OH 45203',
        Lat: 39.1075,
        Lon: -84.5375,
        phone: '(513) 421-8909',
        description:
          'Afterschool programs, mentoring, and youth development for low-income children.',
        hours: 'Mon-Fri 2pm-7pm',
      },
      {
        id: 17,
        resourceType: 'Youth Assistance',
        name: 'Hamilton County Job & Family Services - Youth Employment Services',
        address: '222 E. Central Parkway, Cincinnati, OH 45202',
        Lat: 39.107,
        Lon: -84.512,
        phone: '(513) 946-1000',
        description: 'Summer jobs and career readiness for teens from impoverished households.',
        hours: 'Mon-Fri 8am-4:30pm',
      },
      {
        id: 18,
        resourceType: 'Legal Assistance',
        name: 'Legal Aid Society of Greater Cincinnati',
        address: '215 E. 9th St, Cincinnati, OH 45202',
        Lat: 39.1065,
        Lon: -84.509,
        phone: '(513) 241-9400',
        description:
          'Provides free civil legal services for low-income residents, including housing and benefits cases.',
        hours: 'Mon-Fri 8:30am-5pm',
      },
      {
        id: 19,
        resourceType: 'Legal Assistance',
        name: 'Volunteer Lawyers Project',
        address: '215 E. 9th St, Cincinnati, OH 45202',
        Lat: 39.1065,
        Lon: -84.509,
        phone: '(513) 241-9400',
        description:
          'Pro bono legal services for impoverished individuals facing civil legal issues.',
        hours: 'Mon-Fri 8:30am-5pm',
      },
      {
        id: 20,
        resourceType: 'Legal Assistance',
        name: 'Pro Seniors, Inc.',
        address: '7162 Reading Rd, Suite 1150, Cincinnati, OH 45237',
        Lat: 39.1915,
        Lon: -84.4565,
        phone: '(513) 345-4160',
        description: 'Legal assistance for seniors, including housing, healthcare, and benefits.',
        hours: 'Mon-Fri 8:30am-5pm',
      },
      {
        id: 21,
        resourceType: 'Eviction Assistance',
        name: 'Legal Aid Society Eviction Help Center',
        address: 'Hamilton County Courthouse, 1000 Main St, Cincinnati, OH 45202',
        Lat: 39.106,
        Lon: -84.5105,
        phone: '(513) 241-9400',
        description:
          'Provides free legal defense and tenant advocacy for individuals facing eviction.',
        hours: 'Mon-Fri 8:30am-4pm',
      },
      {
        id: 22,
        resourceType: 'Eviction Assistance',
        name: 'Housing Opportunities Made Equal (HOME)',
        address: '2400 Reading Rd, Suite 210, Cincinnati, OH 45202',
        Lat: 39.1275,
        Lon: -84.5,
        phone: '(513) 721-4663',
        description:
          'Fair housing advocacy and eviction prevention services for low-income tenants.',
        hours: 'Mon-Fri 9am-5pm',
      },
      {
        id: 23,
        resourceType: 'Eviction Assistance',
        name: 'St. Vincent de Paul - Eviction Prevention Program',
        address: '1146 Bank St, Cincinnati, OH 45214',
        Lat: 39.116,
        Lon: -84.5375,
        phone: '(513) 562-8841',
        description: 'Emergency rent assistance to prevent eviction for impoverished families.',
        hours: 'Mon-Fri 8:30am-4pm',
      },
      {
        id: 24,
        resourceType: 'Housing/Eviction Prevention',
        name: 'Bethany House Services',
        address: '1841 Fairmount Ave, Cincinnati, OH 45214',
        Lat: 39.113,
        Lon: -84.537,
        phone: '(513) 921-1131',
        description:
          'Family shelter and housing stabilization programs for homeless and at-risk families.',
        hours: '24/7',
      },
      {
        id: 25,
        resourceType: 'Housing/Eviction Prevention',
        name: 'Interfaith Hospitality Network of Greater Cincinnati',
        address: '990 Nassau St, Cincinnati, OH 45206',
        Lat: 39.1275,
        Lon: -84.48,
        phone: '(513) 471-1100',
        description: 'Emergency shelter and housing case management for homeless families.',
        hours: 'Mon-Fri 9am-5pm',
      },
      {
        id: 26,
        resourceType: 'Housing/Eviction Prevention',
        name: 'Talbert House - Housing Services',
        address: '2600 Victory Parkway, Cincinnati, OH 45206',
        Lat: 39.127,
        Lon: -84.488,
        phone: '(513) 281-2273',
        description:
          'Transitional housing and supportive services for individuals experiencing homelessness.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 27,
        resourceType: 'Free Meals & Pantries',
        name: 'Freestore Foodbank',
        address: '112 E. Liberty St, Cincinnati, OH 45202',
        Lat: 39.115,
        Lon: -84.515,
        phone: '(513) 357-4600',
        description:
          'Largest food pantry in Cincinnati offering groceries and ID vouchers for low-income residents.',
        hours: 'Mon-Fri 8am-3:45pm',
      },
      {
        id: 28,
        resourceType: 'Free Meals & Pantries',
        name: 'Our Daily Bread',
        address: '1730 Race St, Cincinnati, OH 45202',
        Lat: 39.114,
        Lon: -84.52,
        phone: '(513) 621-6364',
        description: 'Serves free hot lunches daily to anyone in need.',
        hours: 'Mon-Fri 10am-12:30pm',
      },
      {
        id: 29,
        resourceType: 'Free Meals & Pantries',
        name: 'St. Francis Seraph Ministries - Soup Kitchen',
        address: '1615 Vine St, Cincinnati, OH 45210',
        Lat: 39.113,
        Lon: -84.517,
        phone: '(513) 535-2719',
        description:
          'Provides free breakfast and dinner meals for homeless and impoverished individuals.',
        hours: 'Mon-Fri breakfast 7am-9am, dinner 4pm-6pm',
      },
      {
        id: 30,
        resourceType: 'Clothing & Household',
        name: 'St. Vincent de Paul Thrift Store & Donation Center',
        address: '1125 Bank St, Cincinnati, OH 45202',
        Lat: 39.1165,
        Lon: -84.537,
        phone: '(513) 421-CARE',
        description:
          'Provides free clothing vouchers and household goods for impoverished families.',
        hours: 'Mon-Sat 9am-8pm, Sun 10am-6pm',
      },
      {
        id: 31,
        resourceType: 'Clothing & Household',
        name: 'Dress for Success Cincinnati',
        address: '4623 Wesley Ave, Cincinnati, OH 45212',
        Lat: 39.163,
        Lon: -84.454,
        phone: '(513) 651-3372',
        description:
          'Professional attire and career coaching for women in poverty seeking employment.',
        hours: 'Mon-Fri 9am-5pm',
      },
      {
        id: 32,
        resourceType: 'Clothing & Household',
        name: 'New Life Furniture Bank',
        address: '11335 Reed Hartman Hwy, Cincinnati, OH 45241',
        Lat: 39.27,
        Lon: -84.387,
        phone: '(513) 313-0530',
        description:
          'Provides gently used furniture to families transitioning out of homelessness.',
        hours: 'Mon-Fri 9am-4pm',
      },
      {
        id: 33,
        resourceType: 'Additional Resources',
        name: 'Community Action Agency of Cincinnati',
        address: '1740 Langdon Farm Rd, Cincinnati, OH 45237',
        Lat: 39.191,
        Lon: -84.456,
        phone: '(513) 569-1840',
        description:
          'Provides utility assistance, workforce programs, and Head Start for low-income families.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 34,
        resourceType: 'Additional Resources',
        name: 'Hamilton County Veterans Service Commission',
        address: '230 E. 9th St, Cincinnati, OH 45202',
        Lat: 39.1065,
        Lon: -84.5095,
        phone: '(513) 946-3300',
        description:
          'Benefits assistance and support for veterans experiencing poverty or homelessness.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 35,
        resourceType: 'Additional Resources',
        name: 'Community Action Agency of Cincinnati',
        address: '1740 Langdon Farm Rd, Cincinnati, OH 45237',
        Lat: 39.191,
        Lon: -84.456,
        phone: '(513) 569-1840',
        description:
          'Provides utility assistance, workforce programs, and Head Start for low-income families.',
        hours: 'Mon-Fri 8am-5pm',
      },
      {
        id: 36,
        resourceType: 'Additional Resources',
        name: 'Hamilton County Veterans Service Commission',
        address: '230 E. 9th St, Cincinnati, OH 45202',
        Lat: 39.1065,
        Lon: -84.5095,
        phone: '(513) 946-3300',
        description:
          'Benefits assistance and support for veterans experiencing poverty or homelessness.',
        hours: 'Mon-Fri 8am-4pm',
      },
      {
        id: 37,
        resourceType: 'Additional Resources',
        name: 'Catholic Charities Southwestern Ohio',
        address: '7162 Reading Rd, Suite 600, Cincinnati, OH 45237',
        Lat: 39.1915,
        Lon: -84.4565,
        phone: '(513) 241-7745',
        description:
          'Offers refugee resettlement, food assistance, and family support services for impoverished communities.',
        hours: 'Mon-Fri 8:30am-5pm',
      },
      {
        id: 38,
        resourceType: 'Additional Resources',
        name: 'Strategies to End Homelessness',
        address: '2368 Victory Parkway, Suite 600, Cincinnati, OH 45206',
        Lat: 39.1272,
        Lon: -84.4885,
        phone: '(513) 263-2780',
        description:
          'Coordinates homeless services across Hamilton County, including shelter referrals and prevention programs.',
        hours: 'Mon-Fri 9am-5pm',
      },
      {
        id: 39,
        resourceType: 'Additional Resources',
        name: 'Greater Cincinnati Homeless Coalition',
        address: '117 E. 12th St, Cincinnati, OH 45202',
        Lat: 39.11,
        Lon: -84.5115,
        phone: '(513) 421-7803',
        description:
          'Advocacy and support network for homeless individuals, connecting them to housing and social services.',
        hours: 'Mon-Fri 9am-5pm',
      },
      {
        id: 40,
        resourceType: 'Additional Resources',
        name: 'United Way 211 Greater Cincinnati',
        address: 'Phone-based service',
        Lat: null,
        Lon: null,
        phone: '211',
        description:
          '24/7 referral hotline connecting homeless and impoverished individuals to shelters, food, and aid.',
        hours: '24/7',
      },
    ]
  );
}
